[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

# Use the latest solc version for our contracts
solc = "0.8.20"

# Solidity version overrides for dependencies
[profile.default.solc_version_overrides]
"lib/v2-core/**/*.sol" = "0.5.16"
"lib/v2-periphery/**/*.sol" = "0.6.6"
